import type {
  Experience,
  Profile,
  Project,
  Stack,
  Tech,
} from "@/types/profile";

export const techs: Tech[] = [
  {
    id: "html5",
    name: "HTML5",
    proficiency: 8,
    keywords: ["html", "html5"],
  },
  {
    id: "css",
    name: "CSS",
    proficiency: 8,
    keywords: ["css"],
  },
  {
    id: "javascript",
    name: "JavaScript",
    proficiency: 7,
    keywords: ["javascript", "js"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    proficiency: 5,
    keywords: ["typescript", "ts"],
  },
  {
    id: "react",
    name: "React",
    proficiency: 6,
    keywords: ["react", "reactjs"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    proficiency: 3,
    keywords: ["next", "nextjs"],
  },
  {
    id: "redux",
    name: "Redux",
    proficiency: 3,
    keywords: ["redux"],
  },
  {
    id: "zod",
    name: "Zod",
    proficiency: 3,
    keywords: ["zod"],
  },
  {
    id: "react-query",
    name: "React Query",
    proficiency: 3,
    keywords: ["react-query", "tanstack"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    proficiency: 3,
    keywords: ["tailwind", "tailwindcss"],
  },
  {
    id: "styled-components",
    name: "Styled Components",
    proficiency: 2,
    keywords: ["styled-components"],
  },
  {
    id: "material-ui",
    name: "Material UI",
    proficiency: 2,
    keywords: ["mui", "material-ui"],
  },
  {
    id: "svelte",
    name: "Svelte",
    proficiency: 1,
    keywords: ["svelte"],
  },
  {
    id: "vue",
    name: "Vue.js",
    proficiency: 1,
    keywords: ["vue", "vuejs"],
  },
  {
    id: "gsap",
    name: "GSAP",
    proficiency: 1,
    keywords: ["gsap"],
  },
  {
    id: "astro",
    name: "Astro",
    proficiency: 1,
    keywords: ["astro"],
  },
  {
    id: "mobile-first",
    name: "Mobile First",
    proficiency: 4,
    keywords: ["mobile-first"],
  },
  {
    id: "pixel-perfect",
    name: "Pixel Perfect",
    proficiency: 1,
    keywords: ["pixel-perfect"],
  },
  {
    id: "atomic-design",
    name: "Atomic Design",
    proficiency: 3,
    keywords: ["atomic-design"],
  },
  {
    id: "storybook",
    name: "Storybook",
    proficiency: 3,
    keywords: ["storybook"],
  },
  {
    id: "jest",
    name: "Jest",
    proficiency: 4,
    keywords: ["jest"],
  },
  {
    id: "testing-library",
    name: "Testing Library",
    proficiency: 4,
    keywords: ["testing-library", "rtl"],
  },
  {
    id: "cypress",
    name: "Cypress",
    proficiency: 1,
    keywords: ["cypress"],
  },
  {
    id: "playwright",
    name: "Playwright",
    proficiency: 1,
    keywords: ["playwright"],
  },
  {
    id: "node",
    name: "Node.js",
    proficiency: 3,
    keywords: ["node", "nodejs"],
  },
  {
    id: "express",
    name: "Express",
    proficiency: 2,
    keywords: ["express"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    proficiency: 2,
    keywords: ["mongodb"],
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    proficiency: 1,
    keywords: ["postgres", "postgresql"],
  },
  {
    id: "supabase",
    name: "Supabase",
    proficiency: 1,
    keywords: ["supabase"],
  },
  {
    id: "firebase",
    name: "Firebase",
    proficiency: 1,
    keywords: ["firebase"],
  },
  {
    id: "rest",
    name: "REST API",
    proficiency: 5,
    keywords: ["rest", "api", "restapi"],
  },
  {
    id: "graphql",
    name: "GraphQL",
    proficiency: 1,
    keywords: ["graphql"],
  },
  {
    id: "react-native",
    name: "React Native",
    proficiency: 3,
    keywords: ["react-native", "rn"],
  },
  {
    id: "flutter",
    name: "Flutter",
    proficiency: 2,
    keywords: ["flutter"],
  },
  {
    id: "git",
    name: "Git",
    proficiency: 8,
    keywords: ["git"],
  },
  {
    id: "github",
    name: "GitHub",
    proficiency: 8,
    keywords: ["github"],
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    proficiency: 3,
    keywords: ["github-actions"],
  },
  {
    id: "gitlab",
    name: "GitLab",
    proficiency: 1,
    keywords: ["gitlab"],
  },
  {
    id: "figma",
    name: "Figma",
    proficiency: 2,
    keywords: ["figma"],
  },
  {
    id: "docker",
    name: "Docker",
    proficiency: 2,
    keywords: ["docker"],
  },
  {
    id: "shadcn",
    name: "shadcn/ui",
    proficiency: 2,
    keywords: ["shadcn", "shadcn-ui"],
  },
  {
    id: "chatgpt",
    name: "ChatGPT SDK",
    proficiency: 2,
    keywords: ["chatgpt", "openai"],
  },
  {
    id: "embeddings",
    name: "Embeddings",
    proficiency: 2,
    keywords: ["embeddings"],
  },
  {
    id: "rhf",
    name: "React Hook Form",
    proficiency: 3,
    keywords: ["react-hook-form", "rhf"],
  },
  {
    id: "auth0",
    name: "Auth0",
    proficiency: 3,
    keywords: ["auth0"],
  },
  {
    id: "uxcam",
    name: "UXCam",
    proficiency: 2,
    keywords: ["uxcam"],
  },
  {
    id: "datadog",
    name: "Datadog",
    proficiency: 2,
    keywords: ["datadog"],
  },
  {
    id: "sse",
    name: "SSE",
    proficiency: 2,
    keywords: ["sse", "server-sent-events"],
  },
  {
    id: "pendo",
    name: "Pendo",
    proficiency: 2,
    keywords: ["pendo"],
  },
  {
    id: "vite",
    name: "Vite",
    proficiency: 2,
    keywords: ["vite"],
  },
  {
    id: "ruby",
    name: "Ruby",
    proficiency: 2,
    keywords: ["ruby"],
  },
  {
    id: "rails",
    name: "Ruby on Rails",
    proficiency: 2,
    keywords: ["rails", "ruby-on-rails"],
  },
  {
    id: "wordpress",
    name: "WordPress",
    proficiency: 2,
    keywords: ["wordpress"],
  },
];

export const stacks: Stack[] = [
  {
    title: "Front-End Development",
    description:
      "Technologies, tools, and practices I use to build modern, responsive, and performant web applications.",
    techIds: [
      "html5",
      "css",
      "javascript",
      "typescript",
      "react",
      "nextjs",
      "redux",
      "zod",
      "react-query",
      "tailwind",
      "styled-components",
      "material-ui",
      "svelte",
      "vue",
      "gsap",
      "astro",
      "mobile-first",
      "pixel-perfect",
      "atomic-design",
    ],
  },
  {
    title: "Front-End Testing",
    description:
      "Unit, integration, and end-to-end testing to ensure reliable and maintainable user interfaces.",
    techIds: ["storybook", "jest", "testing-library", "cypress", "playwright"],
  },
  {
    title: "Back-End Development",
    description:
      "Server-side development focused on APIs, data management, and application logic.",
    techIds: [
      "node",
      "express",
      "mongodb",
      "postgresql",
      "supabase",
      "firebase",
      "rest",
      "graphql",
    ],
  },
  {
    title: "Mobile Development",
    description:
      "Building cross-platform mobile applications with a focus on performance, usability, and code quality.",
    techIds: ["react-native", "flutter"],
  },
  {
    title: "Tools & Workflow",
    description:
      "Technologies and tools I use to design, build, test, and deploy web and mobile applications efficiently.",
    techIds: ["git", "github", "github-actions", "gitlab", "figma", "docker"],
  },
];

export const projects: Project[] = [
  {
    id: "portfolio",
    title: "Portfolio",
    description:
      "This is my portfolio website, where I showcase my work and skills as a software engineer.",
    techIds: ["react", "typescript", "gsap", "tailwind"],
    link: "https://reynaldoqs.github.io/portfolio_spa",
    github: "https://github.com/reynaldoqs/portfolio_spa",
    category: "web",
    rol: "Fullstack Developer",
    priority: "high",
  },
  {
    id: "paw-finder",
    title: "Paw Finder",
    rol: "Fullstack Developer",
    description:
      "PawFinder is a web application designed to help reunite lost pets with their owners. The platform uses image embeddings to analyze and compare pet photos, enabling accurate matching between lost and found pets based on visual similarity.",
    techIds: [
      "react",
      "nextjs",
      "shadcn",
      "supabase",
      "chatgpt",
      "embeddings",
      "tailwind",
      "zod",
      "rhf",
    ],
    link: "https://paw-finder-gold.vercel.app/",
    github: "https://github.com/reynaldoqs/paw-finder",
    category: "web",
    priority: "high",
  },
  {
    id: "cci-dashboard",
    title: "CCI Web Dashboard",
    rol: "Frontend Developer",
    description:
      "CCI is a financial investing platform that lets users open and manage investment accounts, monitor portfolio performance, view transaction history, and track the value and composition of their financial assets.",
    techIds: [
      "react",
      "typescript",
      "redux",
      "rest",
      "graphql",
      "auth0",
      "uxcam",
      "datadog",
      "material-ui",
      "sse",
      "react-query",
      "zod",
      "rhf",
      "storybook",
      "jest",
      "testing-library",
      "playwright",
    ],
    link: "https://dev.cci-non-prod.link/",
    github: "",
    category: "web",
    priority: "medium",
  },
  {
    id: "cci-mobile",
    title: "CCI Mobile App",
    rol: "Mobile Developer",
    description:
      "CCI mobile investing app for account management, portfolio monitoring, and transaction history.",
    techIds: [
      "react-native",
      "typescript",
      "redux",
      "rest",
      "graphql",
      "auth0",
      "uxcam",
      "datadog",
    ],
    link: "https://play.google.com/store/apps/details?id=com.ccimobile",
    github: "",
    category: "mobile",
    priority: "medium",
  },
  {
    id: "shop-your-way",
    title: "Shop Your Way",
    rol: "Mobile Developer",
    description:
      "Online shopping and rewards platform where members earn points on purchases and redeem them for discounts and products.",
    techIds: ["react-native", "typescript", "redux", "rest", "storybook"],
    link: "https://play.google.com/store/apps/details?id=com.sears.shopyourway&hl=en",
    github: "",
    category: "mobile",
    priority: "medium",
  },
  {
    id: "vecinos-app",
    title: "Vecinos App",
    rol: "Mobile Developer",
    description:
      "Platform that connects neighbors with each other and with local businesses.",
    techIds: [
      "react-native",
      "typescript",
      "styled-components",
      "redux",
      "react-query",
      "zod",
      "pendo",
    ],
    link: "https://play.google.com/store/apps/details?id=com.vecinosui",
    github: "",
    category: "mobile",
    priority: "medium",
  },
  {
    id: "vecinos-landing",
    title: "Vecinos Landing Page",
    rol: "Frontend Developer",
    description:
      "Marketing landing page for Vecinos, focused on performance and conversion.",
    techIds: ["react", "typescript", "styled-components", "vite"],
    link: "https://www.vecinos.com/",
    github: "",
    category: "web",
    priority: "low",
  },
  {
    id: "buildout",
    title: "Buildout",
    rol: "Fullstack Developer",
    description:
      "Commercial real estate platform that helps brokers manage listings, marketing, CRM, and workflows.",
    techIds: [
      "react",
      "typescript",
      "tailwind",
      "rails",
      "postgresql",
      "rest",
      "graphql",
      "ruby",
    ],
    link: "https://www.buildout.com/",
    github: "",
    category: "web",
    priority: "low",
  },
  {
    id: "camex-bolivia",
    title: "Camex Bolivia",
    rol: "Intern",
    description:
      "Logistics company website supporting international growth and operations.",
    techIds: ["wordpress", "html5", "css", "javascript"],
    link: "https://camexbolivia.com.bo/",
    github: "",
    category: "web",
    priority: "low",
  },
];

export const experience: Experience[] = [
  {
    company: "CCI Puesto de Bolsa",
    link: "https://cci.com.pa",
    role: "Frontend / Mobile Developer",
    description:
      "Built and maintained CCI investing platform (web and mobile).",
    techIds: ["react", "react-native", "typescript", "redux", "graphql"],
    from: "2021",
    to: "Present",
  },
  {
    company: "Vecinos",
    link: "https://www.vecinos.com/",
    role: "Mobile Developer",
    description: "Developed Vecinos mobile app and landing page.",
    techIds: ["react-native", "react", "typescript", "redux"],
    from: "2019",
    to: "2022",
  },
  {
    company: "Buildout",
    link: "https://www.buildout.com/",
    role: "Fullstack Developer",
    description:
      "Commercial real estate software: listings, CRM, and deal workflows.",
    techIds: ["react", "typescript", "ruby", "rails", "postgresql", "graphql"],
    from: "2018",
    to: "2020",
  },
];

export const profile: Profile = {
  fullName: "Reynaldo Quispe",
  title: "Software Engineer",
  avatar: "/images/avatar.png",
  summary: [
    "UX-focused full stack and mobile developer with 7+ years of experience building user-friendly products for web and mobile.",
    "Background in graphic design and backend development, helping me connect design ideas with solid engineering.",
    "I enjoy turning UX principles into clean, accessible, and scalable interfaces.",
    "I focus on intuitive UI systems with consistent design, usability, and pixel-perfect details.",
  ],
  links: {
    email: "reynaldoqs@gmail.com",
    calendly: "https://calendly.com/reynaldoqs/30min",
    linkedin: "https://www.linkedin.com/in/reynaldoqs/",
    github: "https://github.com/reynaldoqs",
    resume: "/resume.pdf",
  },
  statistics: {
    projects: 23,
    experience: 7,
    clients: 17,
  },
  projects,
  experience,
  stacks,
};
