import buildoutWeb from "@/assets/images/buildout_web.png";
import cciMobile from "@/assets/images/cci_mobile.png";
import portfolioWeb from "@/assets/images/portfolio_web.png";
import sywMobile from "@/assets/images/syw_mobile.png";
import vecinosMoile from "@/assets/images/vecinos_mobile.png";
import type {
  Experience,
  Profile,
  Project,
  Stack,
  Tech,
} from "@/types/profile";

export const techs: Tech[] = [
  {
    id: "html5",
    name: "HTML5",
    proficiency: 8,
    keywords: ["html", "html5"],
  },
  {
    id: "css",
    name: "CSS",
    proficiency: 8,
    keywords: ["css"],
  },
  {
    id: "javascript",
    name: "JavaScript",
    proficiency: 7,
    keywords: ["javascript", "js"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    proficiency: 6,
    keywords: ["typescript", "ts"],
  },
  {
    id: "react",
    name: "React",
    proficiency: 7,
    keywords: ["react", "reactjs"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    proficiency: 4,
    keywords: ["next", "nextjs"],
  },
  {
    id: "redux",
    name: "Redux",
    proficiency: 7,
    keywords: ["redux"],
  },
  {
    id: "zod",
    name: "Zod",
    proficiency: 8,
    keywords: ["zod"],
  },
  {
    id: "react-query",
    name: "React Query",
    proficiency: 6,
    keywords: ["react-query", "tanstack"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    proficiency: 8,
    keywords: ["tailwind", "tailwindcss"],
  },
  {
    id: "styled-components",
    name: "Styled Components",
    proficiency: 5,
    keywords: ["styled-components"],
  },
  {
    id: "material-ui",
    name: "Material UI",
    proficiency: 4,
    keywords: ["mui", "material-ui"],
  },
  {
    id: "svelte",
    name: "Svelte",
    proficiency: 2,
    keywords: ["svelte"],
  },
  {
    id: "vue",
    name: "Vue.js",
    proficiency: 2,
    keywords: ["vue", "vuejs"],
  },
  {
    id: "gsap",
    name: "GSAP",
    proficiency: 8,
    keywords: ["gsap"],
  },
  {
    id: "astro",
    name: "Astro",
    proficiency: 5,
    keywords: ["astro"],
  },
  {
    id: "mobile-first",
    name: "Mobile First",
    proficiency: 9,
    keywords: ["mobile-first"],
  },
  {
    id: "pixel-perfect",
    name: "Pixel Perfect",
    proficiency: 9,
    keywords: ["pixel-perfect"],
  },
  {
    id: "atomic-design",
    name: "Atomic Design",
    proficiency: 9,
    keywords: ["atomic-design"],
  },
  {
    id: "storybook",
    name: "Storybook",
    proficiency: 8,
    keywords: ["storybook"],
  },
  {
    id: "jest",
    name: "Jest",
    proficiency: 7,
    keywords: ["jest"],
  },
  {
    id: "testing-library",
    name: "Testing Library",
    proficiency: 7,
    keywords: ["testing-library", "rtl"],
  },
  {
    id: "cypress",
    name: "Cypress",
    proficiency: 6,
    keywords: ["cypress"],
  },
  {
    id: "playwright",
    name: "Playwright",
    proficiency: 4,
    keywords: ["playwright"],
  },
  {
    id: "node",
    name: "Node.js",
    proficiency: 5,
    keywords: ["node", "nodejs"],
  },
  {
    id: "express",
    name: "Express",
    proficiency: 5,
    keywords: ["express"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    proficiency: 4,
    keywords: ["mongodb"],
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    proficiency: 3,
    keywords: ["postgres", "postgresql"],
  },
  {
    id: "supabase",
    name: "Supabase",
    proficiency: 4,
    keywords: ["supabase"],
  },
  {
    id: "firebase",
    name: "Firebase",
    proficiency: 3,
    keywords: ["firebase"],
  },
  {
    id: "rest",
    name: "REST API",
    proficiency: 7,
    keywords: ["rest", "api", "restapi"],
  },
  {
    id: "graphql",
    name: "GraphQL",
    proficiency: 6,
    keywords: ["graphql"],
  },
  {
    id: "react-native",
    name: "React Native",
    proficiency: 6,
    keywords: ["react-native", "rn"],
  },
  {
    id: "flutter",
    name: "Flutter",
    proficiency: 6,
    keywords: ["flutter"],
  },
  {
    id: "git",
    name: "Git",
    proficiency: 8,
    keywords: ["git"],
  },
  {
    id: "github",
    name: "GitHub",
    proficiency: 8,
    keywords: ["github"],
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    proficiency: 3,
    keywords: ["github-actions"],
  },
  {
    id: "gitlab",
    name: "GitLab",
    proficiency: 2,
    keywords: ["gitlab"],
  },
  {
    id: "figma",
    name: "Figma",
    proficiency: 4,
    keywords: ["figma"],
  },
  {
    id: "docker",
    name: "Docker",
    proficiency: 2,
    keywords: ["docker"],
  },
  {
    id: "shadcn",
    name: "shadcn/ui",
    proficiency: 6,
    keywords: ["shadcn", "shadcn-ui"],
  },
  {
    id: "chatgpt",
    name: "ChatGPT SDK",
    proficiency: 7,
    keywords: ["chatgpt", "openai"],
  },
  {
    id: "embeddings",
    name: "Embeddings",
    proficiency: 2,
    keywords: ["embeddings"],
  },
  {
    id: "rhf",
    name: "React Hook Form",
    proficiency: 5,
    keywords: ["react-hook-form", "rhf"],
  },
  {
    id: "auth0",
    name: "Auth0",
    proficiency: 3,
    keywords: ["auth0"],
  },
  {
    id: "uxcam",
    name: "UXCam",
    proficiency: 5,
    keywords: ["uxcam"],
  },
  {
    id: "datadog",
    name: "Datadog",
    proficiency: 4,
    keywords: ["datadog"],
  },
  {
    id: "sse",
    name: "SSE",
    proficiency: 2,
    keywords: ["sse", "server-sent-events"],
  },
  {
    id: "pendo",
    name: "Pendo",
    proficiency: 2,
    keywords: ["pendo"],
  },
  {
    id: "vite",
    name: "Vite",
    proficiency: 5,
    keywords: ["vite"],
  },
  {
    id: "ruby",
    name: "Ruby",
    proficiency: 2,
    keywords: ["ruby"],
  },
  {
    id: "rails",
    name: "Ruby on Rails",
    proficiency: 2,
    keywords: ["rails", "ruby-on-rails"],
  },
  {
    id: "wordpress",
    name: "WordPress",
    proficiency: 2,
    keywords: ["wordpress"],
  },
  {
    id: "swagger",
    name: "Swagger",
    proficiency: 2,
    keywords: ["swagger"],
  },
  {
    id: "openapi",
    name: "OpenAPI",
    proficiency: 4,
    keywords: ["openapi"],
  },
  {
    id: "ci/cd",
    name: "CI/CD",
    proficiency: 4,
    keywords: ["ci/cd"],
  },
  {
    id: "zustand",
    name: "Zustand",
    proficiency: 8,
    keywords: ["zustand"],
  },
];

export const stacks: Stack[] = [
  {
    title: "Front-End Development",
    description:
      "Technologies, tools, and practices I use to build modern, responsive, and performant web applications.",
    techIds: [
      "html5",
      "css",
      "javascript",
      "typescript",
      "react",
      "nextjs",
      "redux",
      "zod",
      "react-query",
      "tailwind",
      "styled-components",
      "material-ui",
      "svelte",
      "vue",
      "gsap",
      "astro",
      "mobile-first",
      "pixel-perfect",
      "atomic-design",
    ],
  },
  {
    title: "Front-End Testing",
    description:
      "Unit, integration, and end-to-end testing to ensure reliable and maintainable user interfaces.",
    techIds: ["storybook", "jest", "testing-library", "cypress", "playwright"],
  },
  {
    title: "Back-End Development",
    description:
      "Server-side development focused on APIs, data management, and application logic.",
    techIds: [
      "node",
      "express",
      "mongodb",
      "postgresql",
      "supabase",
      "firebase",
      "rest",
      "graphql",
    ],
  },
  {
    title: "Mobile Development",
    description:
      "Building cross-platform mobile applications with a focus on performance, usability, and code quality.",
    techIds: ["react-native", "flutter"],
  },
  {
    title: "Tools & Workflow",
    description:
      "Technologies and tools I use to design, build, test, and deploy web and mobile applications efficiently.",
    techIds: ["git", "github", "github-actions", "gitlab", "figma", "docker"],
  },
];

export const projects: Project[] = [
  {
    id: "portfolio",
    title: "Portfolio",
    description:
      "This is my personal portfolio website, where I showcase my projects, professional experience, and technical skills as a software engineer. It highlights the technologies I work with, the problems I have solved, and the solutions I have built through real-world applications.",
    techIds: [
      "react",
      "nextjs",
      "typescript",
      "zustand",
      "chatgpt",
      "gsap",
      "tailwind",
    ],
    link: "https://reynaldoqs.github.io/portfolio_spa",
    github: "https://github.com/reynaldoqs/portfolio_spa",
    category: "web",
    rol: "Fullstack Developer",
    priority: "high",
    backgroundImage: portfolioWeb,
  },
  {
    id: "paw-finder",
    title: "Paw Finder",
    rol: "Fullstack Developer",
    description:
      "PawFinder is a web application that helps reunite lost pets with their owners by analyzing and comparing pet photos using image embeddings to find visually similar matches.",
    techIds: [
      "nextjs",
      "shadcn",
      "supabase",
      "chatgpt",
      "embeddings",
      "tailwind",
      "zod",
      "rhf",
    ],
    link: "https://paw-finder-gold.vercel.app/",
    github: "https://github.com/reynaldoqs/paw-finder",
    category: "web",
    priority: "medium",
  },
  {
    id: "cci-dashboard",
    title: "CCI Dashboard",
    rol: "Frontend Developer",
    description:
      "CCI is an investment platform that allows users to manage accounts, track portfolio performance, and monitor asset value.",

    techIds: [
      "nextjs",
      "typescript",
      "redux",
      "graphql",
      "auth0",
      "uxcam",
      "datadog",
      "material-ui",
      "react-query",
      "rhf",
      "jest",
    ],
    link: "https://dev.cci-non-prod.link/",
    github: "",
    category: "web",
    priority: "medium",
  },
  {
    id: "cci-mobile",
    title: "CCI Mobile App",
    rol: "Mobile Developer",
    description:
      "CCI mobile investing app for account management, portfolio monitoring, and transaction history.",
    techIds: [
      "react-native",
      "typescript",
      "redux",
      "graphql",
      "auth0",
      "uxcam",
      "datadog",
      "jest",
      "testing-library",
    ],
    link: "https://play.google.com/store/apps/details?id=com.ccimobile",
    github: "",
    category: "mobile",
    priority: "high",
    backgroundImage: cciMobile,
  },
  {
    id: "shop-your-way",
    title: "Shop Your Way",
    rol: "Mobile Developer",
    description:
      "Online shopping and rewards platform where members earn points on purchases and redeem them for discounts and products.",
    techIds: [
      "react-native",
      "typescript",
      "react-query",
      "zod",
      "redux",
      "rest",
      "storybook",
      "jest",
      "testing-library",
    ],
    link: "https://play.google.com/store/apps/details?id=com.sears.shopyourway&hl=en",
    github: "",
    category: "mobile",
    priority: "medium",
    backgroundImage: sywMobile,
  },
  {
    id: "vecinos-app",
    title: "Vecinos App",
    rol: "Mobile Developer",
    description:
      "Platform that connects neighbors with each other and with local businesses.",
    techIds: [
      "react-native",
      "typescript",
      "rest",
      "redux",
      "react-query",
      "zod",
      "pendo",
    ],
    link: "https://play.google.com/store/apps/details?id=com.vecinosui",
    github: "",
    category: "mobile",
    priority: "medium",
    backgroundImage: vecinosMoile,
  },
  {
    id: "vecinos-landing",
    title: "Vecinos Landing Page",
    rol: "Frontend Developer",
    description:
      "Marketing landing page for Vecinos, focused on performance and conversion.",
    techIds: ["react", "typescript", "styled-components", "vite"],
    link: "https://www.vecinos.com/",
    github: "",
    category: "web",
    priority: "low",
  },
  {
    id: "buildout_web",
    title: "Buildout",
    rol: "Fullstack Developer",
    description:
      "Commercial real estate platform that helps brokers manage listings, marketing, CRM, and workflows.",
    techIds: [
      "react",
      "typescript",
      "tailwind",
      "rails",
      "postgresql",
      "rest",
      "ruby",
    ],
    link: "https://www.buildout.com/",
    github: "",
    category: "web",
    priority: "high",
    backgroundImage: buildoutWeb,
  },
  {
    id: "camex-bolivia",
    title: "Camex Bolivia",
    rol: "Intern",
    description:
      "Logistics company website supporting international growth and operations.",
    techIds: ["wordpress", "html5", "css", "javascript"],
    link: "https://camexbolivia.com.bo/",
    github: "",
    category: "web",
    priority: "low",
  },
];

export const experience: Experience[] = [
  {
    company: "Making Sense",
    link: "https://makingsense.com/",
    role: "Fullstack - Mobile - UX/UI Developer",
    description: [
      "Built and maintained a stock market web application and analytics dashboard using Next.js, with a strong focus on performance, SEO, accessibility (a11y), and scalable component architecture. Implemented data-intensive dashboards by integrating GraphQL APIs and managing server state with React Query, while developing secure authentication and role-based access control (RBAC) with Auth0. Translated Figma designs into pixel-perfect, responsive UIs using Material UI, monitored production performance with UXCam and Datadog, and collaborated closely with backend, product, and design teams to deliver internationalized (i18n), scalable solutions for financial data visualization.",
      "Developed a couponing mobile application for iOS and Android that allows users to redeem reward points for gifts and discounts. Designed and built a scalable component library using React Native and Storybook to improve UI consistency, reusability, and development efficiency. Implemented authentication, push notifications, and in-app purchases, while optimizing front-end performance through efficient state management, lazy loading, and component-level optimizations, using Storybook for isolated development and team collaboration.",
      "Developed a social network mobile application for iOS and Android using React Native, delivering smooth, responsive, and reliable user experiences. Built and maintained a marketing landing page with React.js and Vite, focused on conversion-oriented UI. Managed server state and data fetching with React Query to improve caching and data consistency, implemented authentication, push notifications, and in-app purchases to increase user engagement, and collaborated closely with designers to deliver pixel-perfect UI/UX across both mobile and web platforms.",
    ],
    techIds: [
      "react",
      "react-native",
      "typescript",
      "nextjs",
      "redux",
      "graphql",
      "auth0",
      "uxcam",
      "datadog",
      "material-ui",
      "storybook",
      "react-query",
      "zod",
      "rhf",
      "vite",
      "firebase",
      "supabase",
      "chatgpt",
      "jest",
      "testing-library",
    ],
    from: "2021",
    to: "2025",
  },
  {
    company: "Jala Soft",
    link: "https://www.jalasoft.com/",
    role: "Fullstack Developer",
    description: [
      "Developed and maintained a real estate landing page using React.js with a strong focus on UI/UX, building reusable and maintainable components following KISS, DRY, and SOLID principles. Integrated the front end with Ruby on Rails APIs, managing data fetching, state, and error handling, while collaborating with backend services and cross-functional teams to ensure secure, reliable data flow and deliver features aligned with business goals. Also contributed to CI/CD workflows and deployment processes to ensure stable front-end releases.",
    ],
    techIds: [
      "react",
      "typescript",
      "ruby",
      "rails",
      "rest",
      "ci/cd",
      "html5",
      "css",
    ],
    from: "2019",
    to: "2021",
  },
  {
    company:
      "Agencia de Gobierno Electrónico y Tecnologías de Información y Comunicación",
    link: "https://agetic.gob.bo/",
    role: "Backend Developer",
    description: [
      "Developed government applications focused on backend services supporting national digital platforms, using Vue.js for API integration and validation. Designed, built, and documented RESTful APIs with Swagger (OpenAPI) consumed by multiple government agencies, while implementing and maintaining backend services and system integrations to ensure reliable communication across public platforms and improve system performance and reliability.",
    ],
    techIds: ["vue", "typescript", "rest", "swagger", "openapi"],
    from: "2018",
    to: "2019",
  },
  {
    company: "Camex Bolivia",
    link: "https://www.camexbolivia.com.bo/",
    role: "Intern",
    description: [
      "Designed, implemented, and maintained landing pages and web systems, improving UI, fixing front-end bugs, and ensuring consistent functionality. Updated and optimized WordPress pages for better layout, structure, and responsiveness, while collaborating with the team to translate business needs into front-end solutions.",
    ],
    techIds: ["html5", "css", "wordpress"],
    from: "2017",
    to: "2018",
  },
];

export const profile: Profile = {
  fullName: "Reynaldo Quispe",
  title: "Software Engineer",
  avatar: "/images/avatar.png",
  summary: [
    "UX-focused full stack and mobile developer with 7+ years of experience building user-friendly products for web and mobile.",
    "Background in graphic design and backend development, helping me connect design ideas with solid engineering.",
    "I enjoy turning UX principles into clean, accessible, and scalable interfaces.",
    "I focus on intuitive UI systems with consistent design, usability, and pixel-perfect details.",
  ],
  links: {
    email: "reynaldoqs@gmail.com",
    calendly: "https://calendly.com/reynaldoqs/30min",
    linkedin: "https://www.linkedin.com/in/reynaldoqs/",
    github: "https://github.com/reynaldoqs",
    resume: "/resume.pdf",
  },
  statistics: {
    projects: 23,
    experience: 7,
    clients: 17,
  },
  projects,
  experience,
  stacks,
};
