import type { Profile, Tech } from "@/types/profile";

export const mockProfile: Profile = {
  fullName: "Reynaldo Quispe",
  title: "Software Engineer",
  avatar: "/images/avatar.png",
  summary: [
    "UX-focused full stack and mobile developer with 7+ years of experience building user-friendly products for web and mobile. Background in graphic design and backend development. I enjoy turning UX principles into clean, accessible, and scalable interfaces.",
    "I'm a quick learner and I'm always looking to improve my skills and stay up to date with the latest technologies and trends in the industry.",
  ],
  links: {
    email: "reynaldoqs@gmail.com",
    linkedin: "https://www.linkedin.com/in/reynaldoqs/",
    github: "https://github.com/reynaldoqs",
    calendly: "https://calendly.com/reynaldoqs/30min",
    resume: "/resume.pdf",
  },
  statistics: {
    projects: 23,
    experience: 7,
    clients: 17,
  },
  projects: [
    {
      id: "syw_mobile",
      title: "Portfolio",
      description:
        "This is my portfolio website, where I showcase my work and skills as a software engineer.",
      techIds: ["react", "typescript", "gsap", "tailwind"],
      link: "https://reynaldoqs.github.io/portfolio_spa",
      github: "https://github.com/reynaldoqs/portfolio_spa",
      category: "web",
      rol: "Fullstack Developer",
      priority: "high",
    },
    {
      id: "paw-finder",
      title: "Paw Finder",
      description:
        "Web app to reunite lost pets with owners using image embeddings and AI-powered similarity matching.",
      techIds: ["react", "nextjs", "supabase", "tailwind", "zod", "rhf"],
      link: "https://paw-finder-gold.vercel.app/",
      github: "https://github.com/reynaldoqs/paw-finder",
      category: "web",
      rol: "Fullstack Developer",
      priority: "medium",
    },
    {
      id: "cci-dashboard",
      title: "CCI Web Dashboard",
      description:
        "Financial investing platform for opening accounts, portfolio monitoring, and transaction history.",
      techIds: [
        "react",
        "typescript",
        "redux",
        "graphql",
        "auth0",
        "material-ui",
        "react-query",
        "zod",
        "rhf",
        "storybook",
        "playwright",
      ],
      link: "https://dev.cci-non-prod.link/",
      github: "",
      category: "web",
      rol: "Frontend Developer",
      priority: "medium",
    },
    {
      id: "cci-mobile",
      title: "CCI Mobile App",
      description:
        "Mobile financial investing platform for CCI Puesto de Bolsa with portfolio and transaction management.",
      techIds: ["react-native", "typescript", "redux", "graphql", "auth0"],
      link: "https://play.google.com/store/apps/details?id=com.ccimobile",
      github: "",
      category: "mobile",
      rol: "Mobile Developer",
      priority: "medium",
    },
    {
      id: "vecinos-app",
      title: "Vecinos App",
      description:
        "Platform connecting neighbors with each other and local businesses.",
      techIds: ["react-native", "typescript", "redux", "react-query", "zod"],
      link: "https://play.google.com/store/apps/details?id=com.vecinosui",
      github: "",
      category: "mobile",
      rol: "Mobile Developer",
      priority: "medium",
    },
  ],
  experience: [
    {
      company: "CCI Puesto de Bolsa",
      link: "https://cci.com.pa",
      role: "Frontend / Mobile Developer",
      description:
        "Built and maintained CCI investing platform (web and mobile).",
      techIds: ["react", "react-native", "typescript", "redux", "graphql"],
      from: "2021",
      to: "Present",
    },
    {
      company: "Vecinos",
      link: "https://www.vecinos.com/",
      role: "Mobile Developer",
      description: "Developed Vecinos mobile app and landing page.",
      techIds: ["react-native", "react", "typescript", "redux"],
      from: "2019",
      to: "2022",
    },
    {
      company: "Buildout",
      link: "https://www.buildout.com/",
      role: "Fullstack Developer",
      description:
        "Commercial real estate software: listings, CRM, and deal workflows.",
      techIds: [
        "react",
        "typescript",
        "ruby",
        "rails",
        "postgresql",
        "graphql",
      ],
      from: "2018",
      to: "2020",
    },
  ],
  stacks: [
    {
      title: "Frontend",
      description: "Modern UI engineering with strong DX and accessibility.",
      techIds: [
        "react",
        "typescript",
        "nextjs",
        "tailwind",
        "redux",
        "react-query",
        "zod",
        "rhf",
      ],
    },
    {
      title: "Mobile",
      description: "Cross-platform apps with shared patterns and tooling.",
      techIds: ["react-native"],
    },
    {
      title: "Backend",
      description: "APIs, databases, and production-focused integrations.",
      techIds: ["node", "graphql", "postgresql", "ruby", "rails", "supabase"],
    },
    {
      title: "Testing & UI systems",
      description: "Component-driven development and reliable test coverage.",
      techIds: ["storybook", "jest", "playwright"],
    },
  ],
};

export const mockTechs: Tech[] = [
  {
    id: "react",
    name: "React",
    proficiency: 6,
    keywords: ["react", "reactjs", "hooks", "spa"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    proficiency: 6,
    keywords: ["typescript", "ts", "types"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    proficiency: 4,
    keywords: ["next", "nextjs", "ssr", "ssg"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    proficiency: 4,
    keywords: ["tailwind", "tailwindcss", "css", "utility"],
  },
  {
    id: "gsap",
    name: "GSAP",
    proficiency: 2,
    keywords: ["gsap", "animation", "timeline"],
  },
  {
    id: "redux",
    name: "Redux",
    proficiency: 5,
    keywords: ["redux", "state", "store"],
  },
  {
    id: "react-query",
    name: "React Query",
    proficiency: 3,
    keywords: ["react-query", "tanstack", "query", "cache"],
  },
  {
    id: "zod",
    name: "Zod",
    proficiency: 3,
    keywords: ["zod", "validation", "schema"],
  },
  {
    id: "rhf",
    name: "React Hook Form",
    proficiency: 3,
    keywords: ["react-hook-form", "rhf", "forms"],
  },
  {
    id: "react-native",
    name: "React Native",
    proficiency: 5,
    keywords: ["react-native", "rn", "ios", "android"],
  },
  {
    id: "graphql",
    name: "GraphQL",
    proficiency: 4,
    keywords: ["graphql", "api", "schema"],
  },
  {
    id: "auth0",
    name: "Auth0",
    proficiency: 3,
    keywords: ["auth0", "oauth", "authentication"],
  },
  {
    id: "material-ui",
    name: "Material UI",
    proficiency: 4,
    keywords: ["material-ui", "mui", "components", "design-system"],
  },
  {
    id: "storybook",
    name: "Storybook",
    proficiency: 3,
    keywords: ["storybook", "components", "ui", "docs"],
  },
  {
    id: "playwright",
    name: "Playwright",
    proficiency: 2,
    keywords: ["playwright", "e2e", "browser", "testing"],
  },
  {
    id: "jest",
    name: "Jest",
    proficiency: 4,
    keywords: ["jest", "unit", "testing"],
  },
  {
    id: "node",
    name: "Node.js",
    proficiency: 5,
    keywords: ["node", "nodejs", "backend", "runtime"],
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    proficiency: 4,
    keywords: ["postgres", "postgresql", "sql", "database"],
  },
  {
    id: "ruby",
    name: "Ruby",
    proficiency: 3,
    keywords: ["ruby", "backend"],
  },
  {
    id: "rails",
    name: "Ruby on Rails",
    proficiency: 3,
    keywords: ["rails", "ruby-on-rails", "mvc", "backend"],
  },
  {
    id: "supabase",
    name: "Supabase",
    proficiency: 2,
    keywords: ["supabase", "postgres", "auth", "storage"],
  },
];
