export const mockProfile = {
  fullName: "Reynaldo Quispe",
  title: "Software Engineer",
  avatar: "/images/avatar.png",
  summary:
    "UX-focused full stack and mobile developer with 7+ years of experience building user-friendly products for web and mobile. Background in graphic design and backend development. I enjoy turning UX principles into clean, accessible, and scalable interfaces.",
  links: {
    email: "reynaldoqs@gmail.com",
    linkedin: "https://www.linkedin.com/in/reynaldoqs/",
    github: "https://github.com/reynaldoqs",
    calendly: "https://calendly.com/reynaldoqs/30min",
  },
  statistics: {
    projects: 23,
    experience: 7,
    clients: 17,
  },
  projects: [
    {
      id: "portfolio",
      title: "Portfolio",
      description:
        "This is my portfolio website, where I showcase my work and skills as a software engineer.",
      tech: ["react", "typescript", "gsap", "tailwind"],
      link: "https://reynaldoqs.github.io/portfolio_spa",
      github: "https://github.com/reynaldoqs/portfolio_spa",
      category: "web",
      rol: "Fullstack Developer",
      from: "2024",
      to: "Present",
    },
    {
      id: "paw-finder",
      title: "Paw Finder",
      description:
        "Web app to reunite lost pets with owners using image embeddings and AI-powered similarity matching.",
      tech: ["react", "nextjs", "supabase", "tailwind", "zod", "rhf"],
      link: "https://paw-finder-gold.vercel.app/",
      github: "https://github.com/reynaldoqs/paw-finder",
      category: "web",
      rol: "Fullstack Developer",
      from: "2024",
      to: "2024",
    },
    {
      id: "cci-dashboard",
      title: "CCI Web Dashboard",
      description:
        "Financial investing platform for opening accounts, portfolio monitoring, and transaction history.",
      tech: [
        "react",
        "typescript",
        "redux",
        "graphql",
        "auth0",
        "material-ui",
        "react-query",
        "zod",
        "rhf",
        "storybook",
        "playwright",
      ],
      link: "https://dev.cci-non-prod.link/",
      github: "",
      category: "web",
      rol: "Frontend Developer",
      from: "2022",
      to: "2024",
    },
    {
      id: "cci-mobile",
      title: "CCI Mobile App",
      description:
        "Mobile financial investing platform for CCI Puesto de Bolsa with portfolio and transaction management.",
      tech: ["react-native", "typescript", "redux", "graphql", "auth0"],
      link: "https://play.google.com/store/apps/details?id=com.ccimobile",
      github: "",
      category: "mobile",
      rol: "Mobile Developer",
      from: "2021",
      to: "2024",
    },
    {
      id: "vecinos-app",
      title: "Vecinos App",
      description:
        "Platform connecting neighbors with each other and local businesses.",
      tech: ["react-native", "typescript", "redux", "react-query", "zod"],
      link: "https://play.google.com/store/apps/details?id=com.vecinosui",
      github: "",
      category: "mobile",
      rol: "Mobile Developer",
      from: "2020",
      to: "2022",
    },
  ],
  experience: [
    {
      company: "CCI Puesto de Bolsa",
      link: "https://cci.com.pa",
      role: "Frontend / Mobile Developer",
      description:
        "Built and maintained CCI investing platform (web and mobile).",
      tech: ["react", "react-native", "typescript", "redux", "graphql"],
      from: "2021",
      to: "Present",
    },
    {
      company: "Vecinos",
      link: "https://www.vecinos.com/",
      role: "Mobile Developer",
      description: "Developed Vecinos mobile app and landing page.",
      tech: ["react-native", "react", "typescript", "redux"],
      from: "2019",
      to: "2022",
    },
    {
      company: "Buildout",
      link: "https://www.buildout.com/",
      role: "Fullstack Developer",
      description:
        "Commercial real estate software: listings, CRM, and deal workflows.",
      tech: ["react", "typescript", "ruby", "rails", "postgresql", "graphql"],
      from: "2018",
      to: "2020",
    },
  ],
  skills: [
    {
      id: "react",
      name: "React",
      category: "frontend",
      keywords: ["reactjs", "hooks", "spa", "components"],
    },
    {
      id: "typescript",
      name: "TypeScript",
      category: "frontend",
      keywords: ["ts", "typed"],
    },
    {
      id: "nextjs",
      name: "Next.js",
      category: "frontend",
      keywords: ["next", "ssr", "ssg"],
    },
    {
      id: "tailwind",
      name: "Tailwind CSS",
      category: "frontend",
      keywords: ["tailwindcss", "utility"],
    },
    {
      id: "react-native",
      name: "React Native",
      category: "mobile",
      keywords: ["rn", "mobile", "ios", "android"],
    },
    {
      id: "redux",
      name: "Redux",
      category: "frontend",
      keywords: ["state", "store"],
    },
    {
      id: "graphql",
      name: "GraphQL",
      category: "backend",
      keywords: ["api", "query"],
    },
    {
      id: "zod",
      name: "Zod",
      category: "frontend",
      keywords: ["validation", "schema"],
    },
    {
      id: "rhf",
      name: "React Hook Form",
      category: "frontend",
      keywords: ["forms", "rhf"],
    },
    {
      id: "node",
      name: "Node.js",
      category: "backend",
      keywords: ["nodejs", "server"],
    },
    {
      id: "postgresql",
      name: "PostgreSQL",
      category: "backend",
      keywords: ["postgres", "sql", "db"],
    },
    {
      id: "jest",
      name: "Jest",
      category: "testing",
      keywords: ["unit", "test"],
    },
    {
      id: "playwright",
      name: "Playwright",
      category: "testing",
      keywords: ["e2e", "browser"],
    },
    {
      id: "storybook",
      name: "Storybook",
      category: "testing",
      keywords: ["components", "ui"],
    },
  ],
};
